In [1]:
import numpy as np
np.__version__

'1.18.1'

In [6]:
v1=np.array([-1,4])
v1

array([-1,  4])

In [8]:
#daje długość wektora w przestrzeni R^2
np.linalg.norm(v1)

4.123105625617661

In [10]:
#długosc wektora w przestrzeni R^3
v2=np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

In [11]:
#odległość punktu p i q
p=np.array([3,0])
q=np.array([0,4])
np.linalg.norm(p-q)

5.0

In [12]:
#odległość punktu p i q w R^3
p=np.array([3,0,1])
q=np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

In [13]:
#MNOŻENIE MACIERZY

In [15]:
X=np.array([[5,3],[3,9]])
Y=np.array([[1],[-1]])
print(X,'\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [16]:
Z=np.dot(X,Y)
Z

array([[ 2],
       [-6]])

In [17]:
Z.shape

(2, 1)

In [18]:
X=np.array([[2,-1,3],
            [3,1,0]])

Y=np.array([[2,1,-1],
            [0,-1,2],
            [3,2,0]])

In [19]:
np.dot(X,Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [20]:
#WYZNACZNIK MACIERZY

In [21]:
A=np.array([[2,4],[-1,3]])
round(np.linalg.det(A))
#round to jest przybliżenie bo jest pewna niedokładność

10.0

In [22]:
#Ślad macierzy to suma liczb na przekątnej głównej
A=np.array([[2,4],[-1,3]])
np.trace(A)

5

In [23]:
#generaujemy macierz jednostkowa
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
#macierz odwrotna
B=np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [29]:
#ustawiamy precyzje na 4 liczbe po przecinku i wartość suppress na True wyłącza nam notację dziesiętną
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [30]:
#taki sam wynik, bo AB=BA=I, gdzie macierz B to ta odwrotna.
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [31]:
#TRANSPONOWANIE MACIERZY

In [32]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [33]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [34]:
#ROZWIĄZYWANIE UKŁADÓW RÓWNAŃ

In [38]:
#2x+4y=10
#x-y=-1
#rozwiazujego ten układ równań
A=np.array([[2,4],
            [1,-1]])
B=np.array([[10],[-1]])
A1=np.linalg.inv(A)
C=np.dot(A1,B)
C

array([[1.],
       [2.]])